In [39]:
from google import genai
from openai import OpenAI
import ollama
#from google.generativeai import types
import pandas as pd
import json
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv()

True

In [40]:


try:
    df_ts = pd.read_excel('summarized_timeSheet_Feb02-06.xlsx')
    # Optional: Display the first few rows to confirm it loaded correctly
    print("Data loaded successfully:")
    print(df_ts.head())
except FileNotFoundError:
    print(f"Error: ummarized_timeSheet_Feb02-06.xlsx not found. Please check the file path.")
    exit()
except Exception as e:
    print(f"An error occurred while reading the Excel file: {e}")
    exit()

Data loaded successfully:
    Timesheet ID NstarX Emp ID        Employee Name Start Date   End Date  \
0  TS-2026-00529     NSX_C0193   Alessandro Tiberio 2026-02-02 2026-02-06
1  TS-2026-00530     NSX_C0217        Sarika Sharma 2026-02-02 2026-02-03
2  TS-2026-00531     NSX_C0207        Jhanvi Sharma 2026-02-02 2026-02-03
3  TS-2026-00534      NSX_0401  Kontham Anand kumar 2026-02-02 2026-02-06
4  TS-2026-00535      NSX_0436       Apparao Buddha 2026-02-02 2026-02-06

   Total Working Hours              Project Name   Client Name  \
0            32.000000  Populus Data Engineering       Populus
1             9.200556                     Sales   NStarX-SG&A
2             9.250000                     Sales   NStarX-SG&A
3            40.000000     EUC Phase 2 Extension           SHI
4            32.000000    Sustenance Engineering  HealthStream

      Timesheet Approver Timesheet Status
0  Dakshina Murthy Karra             Open
1            Sujay Kumar         Approved
2            Sujay Kumar         Approved
3   Bellum Sai Siva Rama         Approved
4           Amol Patalay             Open

In [41]:
start_date = min(df_ts['Start Date'])
start_date

Timestamp('2026-02-02 00:00:00')

In [42]:
try:
    df_emp= pd.read_excel('report.xlsx')

    print("Employees data loaded successfully")
    print(df_emp)

except FileNotFoundError:
    print(f"Error: report.xlsx not found. Please check the file path.")
    exit()
except Exception as e:
    print(f"An error occurred while reading the Excel file: {e}")
    exit()

Employees data loaded successfully
                 Employee Name                    Employee Email  \
0                 Shayne Pinto        shayne.pinto@nstarxinc.com
1                Tanishq Swami       tanishq.swami@nstarxinc.com
2                         Amol        amol.patalay@nstarxinc.com
3             Sachin Chaudhari    sachin.chaudhari@nstarxinc.com
4    Sujikar Reddy Varidireddy       sujikar.reddy@nstarxinc.com
..                         ...                               ...
115              Raju Pasunuri       raju.pasunuri@nstarxinc.com
116                Ayush Kumar         ayush.kumar@nstarxinc.com
117            Gurunath Kamale     gurunath.kamale@nstarxinc.com
118         Srigiri Sai Manish      manish.srigiri@nstarxinc.com
119         Vaishnavi Anaboina  vaishnavi.anaboina@nstarxinc.com

                  Manager Name Location
0               Ganesh Tyagali       US
1    Bommadevara Kavyabharathi    India
2                 Vishal Kumar      NaN
3                 Vishal Kumar       US
4                 Vishal Kumar      NaN
..                         ...      ...
115                Mohin Shaik    India
116                Mohin Shaik    India
117                Mohin Shaik    India
118                Mohin Shaik    India
119                Mohin Shaik    India

[120 rows x 4 columns]

In [43]:
try:
    df_holidays= pd.read_excel('Holidays_NSX.xlsx')

    print("Holidays data loaded successfully")
    print(df_holidays)

except FileNotFoundError:
    print(f"Error: Holidays_NSX.xlsx not found. Please check the file path.")
    exit()
except Exception as e:
    print(f"An error occurred while reading the Excel file: {e}")
    exit()

Holidays data loaded successfully
                   Date                          Holiday  \
0   2026-01-01 00:00:00       Año nuevo / New Year's Day
1   2026-01-02 00:00:00                   Día de la Toma
2   2026-01-06 00:00:00               Epifanía del Señor
3   2026-01-15 00:00:00               Sankranti / Pongal
4   2026-01-26 00:00:00                     Republic Day
5   2026-03-03 00:00:00                             Holi
6   2026-03-19 00:00:00               Ugadi / Gudi Padwa
7   2026-03-27 00:00:00                  Sri Rama Navami
8   2026-04-02 00:00:00                     Jueves Santo
9   2026-04-03 00:00:00      Viernes Santo / Good Friday
10           10-04-2026             Orthodox Good Friday
11           13-04-2026           Orthodox Easter Monday
12  2026-05-01 00:00:00   Fiesta del Trabajo/ Labour Day
13  2026-05-25 00:00:00                     Memorial Day
14  2026-05-27 00:00:00             Eid-ul-Zuha (Bakrid)
15           01-06-2026                   Children’s Day
16  2026-06-04 00:00:00         Fiesta del Corpus Cristi
17  2026-07-04 00:00:00                 Independence Day
18  2026-08-26 00:00:00                Eid Milad-un-Nabi
19  2026-08-28 00:00:00                   Raksha Bandhan
20  2026-09-04 00:00:00          Sri Krishna Janmashtami
21  2026-09-07 00:00:00                        Labor Day
22  2026-09-14 00:00:00               Vinayaka Chaturthi
23  2026-10-02 00:00:00           Mahatma Gandhi Jayanti
24  2026-10-12 00:00:00        Fiesta Nacional de España
25  2026-10-20 00:00:00        Dussehra (Vijaya Dashami)
26  2026-11-26 00:00:00                 ThanksGiving Day
27  2026-11-27 00:00:00          Day after Thanks Giving
28           30-11-2026                 St. Andrew’s Day
29           01-12-2026                     National Day
30  2026-12-08 00:00:00            Inmaculada Concepción
31  2026-12-25 00:00:00  Natividad del Señor / Christmas
32           26-12-2026          Second Day of Christmas

                     Location Country Optional Half of Year
0   Spain, India, US, Romania, Canada       No          NaN
1                      Spain, Romania       No          NaN
2                               Spain       No          NaN
3                               India       No          NaN
4                               India       No          NaN
5                               India      Yes   First Half
6                               India       No          NaN
7                               India      Yes   First Half
8                               Spain       No          NaN
9                        Spain, India       No          NaN
10                            Romania       No          NaN
11                            Romania       No          NaN
12                     Spain, Romania       No          NaN
13                                 US       No          NaN
14                              India       No          NaN
15                            Romania       No          NaN
16                              Spain       No          NaN
17                                 US       No          NaN
18                              India      Yes  Second Half
19                              India      Yes  Second Half
20                              India      Yes  Second Half
21                         US, Canada      Yes          NaN
22                              India       No          NaN
23                              India       No          NaN
24                              Spain       No          NaN
25                              India       No          NaN
26                         US, Canada       No          NaN
27                                 US       No          NaN
28                            Romania       No          NaN
29                            Romania       No          NaN
30                              Spain       No          NaN
31  Spain, Romania, India, US, Canada       No          NaN
32                            Romania       No          NaN

In [44]:
try:
    df_leaves= pd.read_excel('leaves_Feb02-06.xlsx')

    print("Leaves data loaded successfully")
    print(df_leaves)

except FileNotFoundError:
    print(f"Error: leaves_Feb02-06.xlsx not found. Please check the file path.")
    exit()
except Exception as e:
    print(f"An error occurred while reading the Excel file: {e}")
    exit()

Leaves data loaded successfully
                 name      employee               employee_name  \
0   HR-LAP-2026-00102  HR-EMP-00154             Ganesh Vallamla
1   HR-LAP-2026-00103  HR-EMP-00014            Ramagiri Saiteja
2   HR-LAP-2026-00105  HR-EMP-00039             Kotturi Supriya
3   HR-LAP-2026-00115  HR-EMP-00046         Pramod Kumar Kodoju
4   HR-LAP-2026-00110  HR-EMP-00051             K Anjali Achary
5   HR-LAP-2026-00017  HR-EMP-00127          Alessandro Tiberio
6   HR-LAP-2026-00106  HR-EMP-00077                Younus Shaik
7   HR-LAP-2026-00108  HR-EMP-00042         Amar Sai Veeravalli
8   HR-LAP-2026-00109  HR-EMP-00007       Mohd Khaja Shujauddin
9   HR-LAP-2026-00111  HR-EMP-00084  Heet Hiteshkumar Gorakhiya
10  HR-LAP-2026-00113  HR-EMP-00009                Vishal Kumar
11  HR-LAP-2026-00114  HR-EMP-00084  Heet Hiteshkumar Gorakhiya
12  HR-LAP-2026-00116  HR-EMP-00153              Apparao Buddha
13  HR-LAP-2026-00117  HR-EMP-00032               Sindhu Pogula
14  HR-LAP-2026-00112  HR-EMP-00084  Heet Hiteshkumar Gorakhiya
15  HR-LAP-2026-00119  HR-EMP-00177          Srigiri Sai Manish
16  HR-LAP-2026-00120  HR-EMP-00040    Tejinderpal Singh Jadhav
17  HR-LAP-2026-00121  HR-EMP-00032               Sindhu Pogula
18  HR-LAP-2026-00122  HR-EMP-00032               Sindhu Pogula
19  HR-LAP-2026-00123  HR-EMP-00010               Amol  Patalay

                    leave_type  from_date    to_date  total_leave_days  \
0    Previous Year Sick Leaves 2026-02-02 2026-02-02               1.0
1   Previous Year Earned Leave 2026-02-02 2026-02-02               1.0
2    Previous Year Sick Leaves 2026-02-02 2026-02-03               2.0
3    Previous Year Sick Leaves 2026-02-02 2026-02-03               2.0
4                   Sick Leave 2026-02-03 2026-02-03               1.0
5                 Annual Leave 2026-02-04 2026-02-04               1.0
6   Previous Year Earned Leave 2026-02-04 2026-02-04               1.0
7                 Earned Leave 2026-02-04 2026-02-05               2.0
8    Previous Year Sick Leaves 2026-02-04 2026-02-04               1.0
9                   Sick Leave 2026-02-04 2026-02-04               0.5
10                Casual Leave 2026-02-04 2026-02-04               1.0
11                Casual Leave 2026-02-05 2026-02-05               1.0
12                  Sick Leave 2026-02-05 2026-02-05               1.0
13                Earned Leave 2026-02-05 2026-02-05               1.0
14                Earned Leave 2026-02-06 2026-02-06               1.0
15                Earned Leave 2026-02-06 2026-02-06               1.0
16                Earned Leave 2026-02-06 2026-02-06               1.0
17                Casual Leave 2026-02-06 2026-02-06               0.5
18                  Sick Leave 2026-02-06 2026-02-06               0.5
19   Previous Year Sick Leaves 2026-02-06 2026-02-06               1.0

      status
0   Approved
1   Approved
2   Approved
3   Approved
4   Approved
5   Approved
6       Open
7   Approved
8   Approved
9   Approved
10  Approved
11  Approved
12  Approved
13  Approved
14  Approved
15      Open
16      Open
17      Open
18      Open
19      Open

In [45]:
ts_as_csv = df_ts.to_csv(index=False)
emp_as_csv = df_emp.to_csv(index=False)
hol_as_csv = df_holidays.to_csv(index=False)
leaves_as_csv = df_leaves.to_csv(index=False)

In [47]:
analysis_prompt = f"""

1. Look into the timesheet records from {ts_as_csv}. 
2. The list of employees is {emp_as_csv}
3. The holidays for each location country is in {hol_as_csv}
4. The list of leaves applied by the employees are in {leaves_as_csv}.
5. The number of working hours in a day is 8 hours. For a given location/country the number of working hours in a week is (5 - holidays in the week) times 8 hours.
6. Calculate the "required number of working hours in the week" according to step 5.
7. For every employee the "required number of working hours" is "required working hours in the week" - (8 times number of leaves he/she applied for)
8. Employees can record their time for the week in one row or they might split their time in muliple rows.
9. If there are multiple records for one 'Employee Name' add up the 'Total Working Hours' for all the rows.
10. For each employee in {emp_as_csv} calculate "Deficiency/Overtime in  Hours" = required working hours in the week - (8 times number of leaves he/she applied for) 
11. Create a json list output string that can be loaded in a python dictionary. The list should include one dictionary for each employee from {emp_as_csv}.
    The keys for each dictionary should be 
    "Name","Location", "Deficiency/Overtime in Hours", "Total Time Logged", "Holiday Hours", "PTO Hours", "Status", "Manager", "Validation Needed","Analysis of Deficiency".
    "Total Time Logged" is same as "Total Working Hours". 
    "Holiday Hours" is 8 times the total number of holidays in the week.
    "PTO Hours" is 8 times the total number of leaves taken by the employee in the week.
    "Status" is same as "Timesheet Status" .
    "Manager is the "Timesheet Approver"
    Include a brief summary of the time logged under "Analysis of Deficiency". 
    If time logged is not equivalet to the required number of working hours then set "Validation Needed" to "Yes". Otherwise "No"
    If the logged hours is less than the required number of working hours, precede the "Deficiency/Overtime in Hours" with a '-'
    If the logged hours is more than the required number of working hours, precede the "Deficiency/Overtime in Hours" with a '+'

12. Do not include any string in the response apart from the json list. 
"""

In [48]:
try:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY environment variable not set.")
    client = genai.Client(api_key=api_key)
except ValueError as e:
    print(f"Configuration error: {e}")
    exit()

In [49]:

response = client.models.generate_content(
    model="gemini-3-flash-preview", # Or a more powerful model like gemini-2.5-pro for complex analysis
    contents=analysis_prompt
    
    
)

In [50]:
print("\n--- Timesheet Report---")
analysis_result = response.text
print(analysis_result)

--- Timesheet Report---
[
  {
    "Name": "Shayne Pinto",
    "Location": "US",
    "Deficiency/Overtime in Hours": "-20.0",
    "Total Time Logged": 20.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Ganesh Tyagali",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "Logged hours (20.0) are less than the required weekly hours (40.0)."
  },
  {
    "Name": "Tanishq Swami",
    "Location": "India",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Bommadevara Kavyabharathi",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Amol",
    "Location": "",
    "Deficiency/Overtime in Hours": "-32.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "Open",
    "Manager": "Vishal Kumar",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "Employee took 8 hours of PTO but did not log the remaining 32.0 required hours."
  },
  {
    "Name": "Sachin Chaudhari",
    "Location": "US",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Vishal Kumar",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Sujikar Reddy Varidireddy",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Vishal Kumar",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Younus Shaik",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 32.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "Open",
    "Manager": "Vishal Kumar",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours plus PTO hours meet the 40-hour requirement."
  },
  {
    "Name": "Manjrekar Manish Raj",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Vishal Kumar",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Bellum Sai Siva Rama Krishna",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Vishal Kumar",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Mohin Shaik",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Vishal Kumar",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Subbaraju",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol  Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Nidhi",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Swaroopa",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Saiteja Ramagiri",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Ramagiri Saiteja",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 32.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "Open",
    "Manager": "Amol  Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours plus PTO hours meet the 40-hour requirement."
  },
  {
    "Name": "Smruthi Kothakonda",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol  Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Sravani Koukuntla",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Jabeen Khanam",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Uday kiran Y",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol  Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Rajan Kumar",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Saiteja Ramagiri",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Dosala Shiva Shankaraiah",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Arun Goluguri",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Saketh Dahagam",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Veena Madhuri",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Naveen Babu Yarlagadda",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Nagasandeep Motupalli",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Shravan Kumar A S",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Hariteja  Eeraparaju",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Suresh Goparaju",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Chappidi Subba Raju",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Venkat Pogakula",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Thota Naresh",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Ashok Munagala",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Sampath Gattu",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Deepak Devaraj",
    "Location": "US",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol  Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Sai Srinivas Potla",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Geethika Kakarla",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Narayana Reddy Bogireddy",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Apparao Buddha",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 32.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours plus PTO hours meet the 40-hour requirement."
  },
  {
    "Name": "Ganesh Vallamla",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 32.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours plus PTO hours meet the 40-hour requirement."
  },
  {
    "Name": "Sriram Narayan",
    "Location": "India",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Venkat Murthy Velamala",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Amol Patalay",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Chaitanya Dhanalakota",
    "Location": "India",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Tejaswini Kande",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Subbaraju Chappidi",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Sirisha Achnala",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Chappidi Subba Raju",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Siva Reddy Evuri",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Chappidi Subba Raju",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Kotla Pavani Priyanka",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Chappidi Subba Raju",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "SwamiNaidu Seepana",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Chappidi Subba Raju",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Raghava Harshavardhan Raju",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Chappidi Subba Raju",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Mohd Khaja Shujauddin",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 32.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "Approved",
    "Manager": "Saiteja Ramagiri",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours plus PTO hours meet the 40-hour requirement."
  },
  {
    "Name": "Tejaswani Kambampati",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Saiteja Ramagiri",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Keertipati Chandu Varma",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Saiteja Ramagiri",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Chandana Gidugu",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Saiteja Ramagiri",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Prajakta Shikare Maruti",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Saiteja Ramagiri",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Amar Sai Veeravalli",
    "Location": "India",
    "Deficiency/Overtime in Hours": "-24.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 16,
    "Status": "None",
    "Manager": "Ramagiri Saiteja",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "Employee took 16 hours of PTO but failed to log the remaining 24 required hours."
  },
  {
    "Name": "Sai Krishna Andhavarapu",
    "Location": "India",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Saiteja Ramagiri",
    "Validation Needed": "No",
    "Analysis of Deficiency": "Logged hours meet the required 40 hours."
  },
  {
    "Name": "Anveshitha Thota",
    "Location": "India",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Ramagiri Saiteja",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Nuty Vanitha",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Smruthi Kothakonda",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Devadula Sai Sudheer",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Smruthi Kothakonda",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Gouni Saideepthi",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Smruthi Kothakonda",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Bera Sireesha Krishnaveni",
    "Location": "",
    "Deficiency/Overtime in Hours": "-40.0",
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Smruthi Kothakonda",
    "Validation Needed": "Yes",
    "Analysis of Deficiency": "No hours logged for the week."
  },
  {
    "Name": "Venkata Lalitha Suresh Emani",
    "Location": "",
    "Deficiency/Overtime in Hours": "0.0",
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,

In [51]:
emp_lst = json.loads(analysis_result)

In [52]:
print(len(emp_lst))
for dict in emp_lst:
    print(dict)

120
{'Name': 'Shayne Pinto', 'Location': 'US', 'Deficiency/Overtime in Hours': '-20.0', 'Total Time Logged': 20.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Ganesh Tyagali', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'Logged hours (20.0) are less than the required weekly hours (40.0).'}
{'Name': 'Tanishq Swami', 'Location': 'India', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Bommadevara Kavyabharathi', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Amol', 'Location': '', 'Deficiency/Overtime in Hours': '-32.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 8, 'Status': 'Open', 'Manager': 'Vishal Kumar', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'Employee took 8 hours of PTO but did not log the remaining 32.0 required hours.'}
{'Name': 'Sachin Chaudhari', 'Location': 'US', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Vishal Kumar', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Sujikar Reddy Varidireddy', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Vishal Kumar', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Younus Shaik', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 32.0, 'Holiday Hours': 0, 'PTO Hours': 8, 'Status': 'Open', 'Manager': 'Vishal Kumar', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours plus PTO hours meet the 40-hour requirement.'}
{'Name': 'Manjrekar Manish Raj', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Vishal Kumar', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Bellum Sai Siva Rama Krishna', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Vishal Kumar', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Mohin Shaik', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Vishal Kumar', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Subbaraju', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol  Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Nidhi', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Swaroopa', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Saiteja Ramagiri', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Ramagiri Saiteja', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 32.0, 'Holiday Hours': 0, 'PTO Hours': 8, 'Status': 'Open', 'Manager': 'Amol  Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours plus PTO hours meet the 40-hour requirement.'}
{'Name': 'Smruthi Kothakonda', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol  Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Sravani Koukuntla', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Jabeen Khanam', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Uday kiran Y', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol  Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Rajan Kumar', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Approved', 'Manager': 'Saiteja Ramagiri', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Dosala Shiva Shankaraiah', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Arun Goluguri', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Saketh Dahagam', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Veena Madhuri', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Naveen Babu Yarlagadda', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Nagasandeep Motupalli', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Shravan Kumar A S', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Hariteja  Eeraparaju', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Suresh Goparaju', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Approved', 'Manager': 'Chappidi Subba Raju', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Venkat Pogakula', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Thota Naresh', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Ashok Munagala', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Sampath Gattu', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Deepak Devaraj', 'Location': 'US', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol  Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Sai Srinivas Potla', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Geethika Kakarla', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Narayana Reddy Bogireddy', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Apparao Buddha', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 32.0, 'Holiday Hours': 0, 'PTO Hours': 8, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours plus PTO hours meet the 40-hour requirement.'}
{'Name': 'Ganesh Vallamla', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 32.0, 'Holiday Hours': 0, 'PTO Hours': 8, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours plus PTO hours meet the 40-hour requirement.'}
{'Name': 'Sriram Narayan', 'Location': 'India', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Venkat Murthy Velamala', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Chaitanya Dhanalakota', 'Location': 'India', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Tejaswini Kande', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Subbaraju Chappidi', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Sirisha Achnala', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Approved', 'Manager': 'Chappidi Subba Raju', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Siva Reddy Evuri', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Chappidi Subba Raju', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Kotla Pavani Priyanka', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Chappidi Subba Raju', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'SwamiNaidu Seepana', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Chappidi Subba Raju', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Raghava Harshavardhan Raju', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Chappidi Subba Raju', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Mohd Khaja Shujauddin', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 32.0, 'Holiday Hours': 0, 'PTO Hours': 8, 'Status': 'Approved', 'Manager': 'Saiteja Ramagiri', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours plus PTO hours meet the 40-hour requirement.'}
{'Name': 'Tejaswani Kambampati', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Approved', 'Manager': 'Saiteja Ramagiri', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Keertipati Chandu Varma', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Saiteja Ramagiri', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Chandana Gidugu', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Approved', 'Manager': 'Saiteja Ramagiri', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Prajakta Shikare Maruti', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Approved', 'Manager': 'Saiteja Ramagiri', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Amar Sai Veeravalli', 'Location': 'India', 'Deficiency/Overtime in Hours': '-24.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 16, 'Status': 'None', 'Manager': 'Ramagiri Saiteja', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'Employee took 16 hours of PTO but failed to log the remaining 24 required hours.'}
{'Name': 'Sai Krishna Andhavarapu', 'Location': 'India', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Saiteja Ramagiri', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Anveshitha Thota', 'Location': 'India', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Ramagiri Saiteja', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Nuty Vanitha', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Smruthi Kothakonda', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Devadula Sai Sudheer', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Smruthi Kothakonda', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Gouni Saideepthi', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Smruthi Kothakonda', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Bera Sireesha Krishnaveni', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Smruthi Kothakonda', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Venkata Lalitha Suresh Emani', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Sindhu Pogula', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 24.0, 'Holiday Hours': 0, 'PTO Hours': 16, 'Status': 'Open', 'Manager': 'Uday kiran Y', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours plus PTO hours meet the 40-hour requirement.'}
{'Name': 'Ramesh Bevara', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Naresh Sowoju', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Amol Patalay', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Rajeshwar', 'Location': '', 'Deficiency/Overtime in Hours': '0.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Approved', 'Manager': 'Syam Sundar Devarakonda', 'Validation Needed': 'No', 'Analysis of Deficiency': 'Logged hours meet the required 40 hours.'}
{'Name': 'Pramod Kumar Kodoju', 'Location': '', 'Deficiency/Overtime in Hours': '-24.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 16, 'Status': 'None', 'Manager': 'Syam Sundar Devarakonda', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'Employee took 16 hours of PTO but failed to log the remaining 24 required hours.'}
{'Name': 'Babita Kumar', 'Location': '', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Syam Sundar Devarakonda', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Jesus Fernandez', 'Location': 'Spain', 'Deficiency/Overtime in Hours': '-40.0', 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Syam Sundar Devarakonda', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'No hours logged for the week.'}
{'Name': 'Vishal Kumar', 'Location': '', 'Deficiency/Overtime in Hours': '+8.0', 'Total Time Logged': 40.0, 'Holiday Hours': 0, 'PTO Hours': 8, 'Status': 'Open', 'Manager': 'Angshuman Patra', 'Validation Needed': 'Yes', 'Analysis of Deficiency': 'Logged 40 hours while only 32 were required due to PTO.'}

In [53]:
df_report = pd.DataFrame(emp_lst)
df_report.head()

,Name,Location,Deficiency/Overtime in Hours,Total Time Logged,Holiday Hours,PTO Hours,Status,Manager,Validation Needed,Analysis of Deficiency
0,Shayne Pinto,US,-20.0,20.0,0,0,Open,Ganesh Tyagali,Yes,Logged hours (20.0) are less than the required...
1,Tanishq Swami,India,-40.0,0.0,0,0,None,Bommadevara Kavyabharathi,Yes,No hours logged for the week.
2,Amol,,-32.0,0.0,0,8,Open,Vishal Kumar,Yes,Employee took 8 hours of PTO but did not log t...
3,Sachin Chaudhari,US,-40.0,0.0,0,0,None,Vishal Kumar,Yes,No hours logged for the week.
4,Sujikar Reddy Varidireddy,,-40.0,0.0,0,0,None,Vishal Kumar,Yes,No hours logged for the week.

In [54]:
report_as_csv = df_report.to_csv(index=False)

In [55]:
defaulters_search_prompt = f"""

1. Look into the reports records from {report_as_csv}. 
2. The list of employees is {emp_as_csv}
3. Look for employees who did not file required number of hours in the column "Deficiency/Overtime in Hours".
4. For the defaulters the column "Validation Needed" should be "Yes".
5. Create a json list output string that can be loaded in a python dictionary. The list should include one dictionary defaulter found in step 4.
6. The keys for each dictionary should be 
    "Name","Location", "Deficiency/Overtime in Hours", "Total Time Logged", "Holiday Hours", "PTO Hours", "Status", "Manager","Week Defaulted".
7. All the matching columns in step 6 should be as they are in {report_as_csv}.
8. The column "Week Defaulted" should be the last working date ("DD-MM-YYYY")of the week starting on {start_date}.
9. Do not include any string in the response apart from the json list. 
"""

In [56]:
response = client.models.generate_content(
    model="gemini-3-flash-preview", # Or a more powerful model like gemini-2.5-pro for complex analysis
    contents=defaulters_search_prompt
)

In [57]:
print("\n--- Defaulters Search---")
defaulters_result = response.text
print(defaulters_result)
defaulters_lst = json.loads(defaulters_result)
print(len(defaulters_lst))
for dict in defaulters_lst:
    print(dict)

--- Defaulters Search---
[
  {
    "Name": "Shayne Pinto",
    "Location": "US",
    "Deficiency/Overtime in Hours": -20.0,
    "Total Time Logged": 20.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Ganesh Tyagali",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Tanishq Swami",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Bommadevara Kavyabharathi",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Amol",
    "Location": "",
    "Deficiency/Overtime in Hours": -32.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "Open",
    "Manager": "Vishal Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sachin Chaudhari",
    "Location": "US",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Vishal Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sujikar Reddy Varidireddy",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Vishal Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Nidhi",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sravani Koukuntla",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Arun Goluguri",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Veena Madhuri",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Naveen Babu Yarlagadda",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Nagasandeep Motupalli",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Shravan Kumar A S",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Hariteja  Eeraparaju",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Venkat Pogakula",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sampath Gattu",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sriram Narayan",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Chaitanya Dhanalakota",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Amol  Patalay",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Tejaswini Kande",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Subbaraju Chappidi",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Amar Sai Veeravalli",
    "Location": "India",
    "Deficiency/Overtime in Hours": -24.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 16,
    "Status": "None",
    "Manager": "Ramagiri Saiteja",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Anveshitha Thota",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Ramagiri Saiteja",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Nuty Vanitha",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Smruthi Kothakonda",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Devadula Sai Sudheer",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Smruthi Kothakonda",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Gouni Saideepthi",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Smruthi Kothakonda",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Bera Sireesha Krishnaveni",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Smruthi Kothakonda",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Pramod Kumar Kodoju",
    "Location": "",
    "Deficiency/Overtime in Hours": -24.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 16,
    "Status": "None",
    "Manager": "Syam Sundar Devarakonda",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Babita Kumar",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Syam Sundar Devarakonda",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Jesus Fernandez",
    "Location": "Spain",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Syam Sundar Devarakonda",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Vishal Kumar",
    "Location": "",
    "Deficiency/Overtime in Hours": 8.0,
    "Total Time Logged": 40.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "Open",
    "Manager": "Angshuman Patra",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Nikhil Sham Vanjari",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Sujikar Reddy Varidireddy",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sreelakshmi Kammakattu",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Sujikar Reddy Varidireddy",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Britney H",
    "Location": "",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Sujikar Reddy Varidireddy",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sai Vyvaswath Bhupasamudram",
    "Location": "India",
    "Deficiency/Overtime in Hours": -8.0,
    "Total Time Logged": 32.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Kriti Bhagat",
    "Location": "India",
    "Deficiency/Overtime in Hours": 4.983056,
    "Total Time Logged": 44.983056,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Open",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Meena Nagarajan",
    "Location": "US",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Dakshina Murthy Karra",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Navdeep Singh",
    "Location": "",
    "Deficiency/Overtime in Hours": -31.0,
    "Total Time Logged": 9.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Sujay Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Jhanvi Sharma",
    "Location": "",
    "Deficiency/Overtime in Hours": 6.400001,
    "Total Time Logged": 46.400001,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Sujay Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Saloni Singh Andotra",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Sujay Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Anchal Bakshi",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Sujay Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Afrin Taj",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Sujay Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sarika Sharma",
    "Location": "India",
    "Deficiency/Overtime in Hours": -2.8075,
    "Total Time Logged": 37.1925,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "Approved",
    "Manager": "Sujay Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "MN Prasad Reddy",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Sujay Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Dakshina Murthy Karra",
    "Location": "US",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Babita Kumar",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sidharth Kondapuram",
    "Location": "Spain",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Jesus Fernandez",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Akunuri Jai Tiru Ganesh",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Manjrekar Manish Raj",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Abhirupa Sen",
    "Location": "US",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Shayne Pinto",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Suneel Kumar Reddy Vaka",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Bellum Sai Siva Rama Krishna",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Manish Gari",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Bellum Sai Siva Rama Krishna",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Tejinderpal Singh Jadhav",
    "Location": "India",
    "Deficiency/Overtime in Hours": -32.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "None",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Rohit Kumar",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Shantanu Chaturvedi",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Heet Hiteshkumar Gorakhiya",
    "Location": "India",
    "Deficiency/Overtime in Hours": -20.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 20,
    "Status": "None",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Sowmya Kunapuli",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Srigiri Sai Manish",
    "Location": "India",
    "Deficiency/Overtime in Hours": -32.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 8,
    "Status": "None",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  },
  {
    "Name": "Vaishnavi Anaboina",
    "Location": "India",
    "Deficiency/Overtime in Hours": -40.0,
    "Total Time Logged": 0.0,
    "Holiday Hours": 0,
    "PTO Hours": 0,
    "Status": "None",
    "Manager": "Mohin Shaik",
    "Week Defaulted": "06-02-2026"
  }
]
54
{'Name': 'Shayne Pinto', 'Location': 'US', 'Deficiency/Overtime in Hours': -20.0, 'Total Time Logged': 20.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'Open', 'Manager': 'Ganesh Tyagali', 'Week Defaulted': '06-02-2026'}
{'Name': 'Tanishq Swami', 'Location': 'India', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Bommadevara Kavyabharathi', 'Week Defaulted': '06-02-2026'}
{'Name': 'Amol', 'Location': '', 'Deficiency/Overtime in Hours': -32.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 8, 'Status': 'Open', 'Manager': 'Vishal Kumar', 'Week Defaulted': '06-02-2026'}
{'Name': 'Sachin Chaudhari', 'Location': 'US', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Vishal Kumar', 'Week Defaulted': '06-02-2026'}
{'Name': 'Sujikar Reddy Varidireddy', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Vishal Kumar', 'Week Defaulted': '06-02-2026'}
{'Name': 'Nidhi', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Sravani Koukuntla', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Arun Goluguri', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Veena Madhuri', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Naveen Babu Yarlagadda', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Nagasandeep Motupalli', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Shravan Kumar A S', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Hariteja  Eeraparaju', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Venkat Pogakula', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Sampath Gattu', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Sriram Narayan', 'Location': 'India', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Chaitanya Dhanalakota', 'Location': 'India', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Amol  Patalay', 'Week Defaulted': '06-02-2026'}
{'Name': 'Tejaswini Kande', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Subbaraju Chappidi', 'Week Defaulted': '06-02-2026'}
{'Name': 'Amar Sai Veeravalli', 'Location': 'India', 'Deficiency/Overtime in Hours': -24.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 16, 'Status': 'None', 'Manager': 'Ramagiri Saiteja', 'Week Defaulted': '06-02-2026'}
{'Name': 'Anveshitha Thota', 'Location': 'India', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Ramagiri Saiteja', 'Week Defaulted': '06-02-2026'}
{'Name': 'Nuty Vanitha', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Smruthi Kothakonda', 'Week Defaulted': '06-02-2026'}
{'Name': 'Devadula Sai Sudheer', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Smruthi Kothakonda', 'Week Defaulted': '06-02-2026'}
{'Name': 'Gouni Saideepthi', 'Location': '', 'Deficiency/Overtime in Hours': -40.0, 'Total Time Logged': 0.0, 'Holiday Hours': 0, 'PTO Hours': 0, 'Status': 'None', 'Manager': 'Smruthi Kothakonda', 'Week Defaulted': '06-02-2026'}

In [58]:
df_defaulters = pd.DataFrame(defaulters_lst)
df_defaulters.head()

,Name,Location,Deficiency/Overtime in Hours,Total Time Logged,Holiday Hours,PTO Hours,Status,Manager,Week Defaulted
0,Shayne Pinto,US,-20.0,20.0,0,0,Open,Ganesh Tyagali,06-02-2026
1,Tanishq Swami,India,-40.0,0.0,0,0,None,Bommadevara Kavyabharathi,06-02-2026
2,Amol,,-32.0,0.0,0,8,Open,Vishal Kumar,06-02-2026
3,Sachin Chaudhari,US,-40.0,0.0,0,0,None,Vishal Kumar,06-02-2026
4,Sujikar Reddy Varidireddy,,-40.0,0.0,0,0,None,Vishal Kumar,06-02-2026

In [35]:
file_path = "Defaulters_Jan26-Feb06.xlsx"
sheet_name = "Sheet1"

if os.path.exists(file_path):
    # 1. Load existing data
    existing_defaulters = pd.read_excel(file_path, sheet_name=sheet_name)

    # 2. Combine existing and new data
    combined_defaulters = pd.concat([existing_defaulters, df_defaulters], ignore_index=True)
else:
    # If the file doesn't exist, the new data is the combined data
    combined_defaulters = df_defaulters

# 3. Save the combined DataFrame back to the Excel file
# Use 'if_sheet_exists="replace"' to overwrite the specific sheet
with pd.ExcelWriter(file_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    combined_defaulters.to_excel(writer, sheet_name=sheet_name, index=False)

print(f"Data appended to {file_path} in sheet '{sheet_name}'.")

Data appended to Defaulters_Jan26-Feb06.xlsx in sheet 'Sheet1'.

In [59]:
try:
    with pd.ExcelWriter("Weekly_Report_Feb02-06.xlsx", engine='openpyxl') as writer:
        df_report.to_excel(writer, sheet_name='Timesheet Report Feb 02-06', index=False)
        df_defaulters.to_excel(writer, sheet_name='Defaulters Feb 02-06', index=False)

    print(f"Successfully created '{"Weekly_Report_Feb02-06.xlsx"}' with multiple sheets.")

except Exception as e:
    print(f"An error occurred: {e}")

Successfully created 'Weekly_Report_Feb02-06.xlsx' with multiple sheets.

In [60]:
import smtplib
from email.message import EmailMessage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

In [61]:
## sending the email
sender = os.getenv("EMAIL_USER")
password = os.getenv("EMAIL_PASS")
receiver = os.getenv("EMAIL_TO")
#receiver = "abhirupac.sen@gmail.com"

#smtp_server = "smtp.gmail.com"
#smtp_port = 465 

file_to_attach = "Weekly_Report_Feb02-06.xlsx"
try:
        

        body = "Hi Shayne, \n Attached is file with timesheet report and defaulters from Jan 26 to Feb 06, 2026. I am sending this email from python code.\n\nThanks,\nAbhirupa"
        msg = MIMEMultipart()
        msg['Subject'] = "Timesheet Report and Defaulters from Feb 02 to Feb 06, 2026"
        msg['From'] = sender
        msg['To'] = receiver
        msg.attach(MIMEText(body, "plain"))

        part = MIMEBase("application", "vnd.openxmlformats-officedocument.spreadsheetml.sheet")

        with open(file_to_attach, "rb") as attachment:
            # MIMEBase handles binary files like Excel
            #part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())

        # Encode file in ASCII characters to send by email    
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f'attachment; filename="{os.path.basename(file_to_attach)}"'
        )
        msg.attach(part)

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls() # Secure the connection
        server.login(sender, password)
        server.send_message(msg)

except Exception as e:
        print(f"Failed to send emails: {e}")